services:
  - type: web
    name: jeux-eco
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.4
    plan: free
    autoDeploy: true
